export type Sector = "Finance" | "Tech" | "Industrial" | "Energy" | "Healthcare" | "Consumer";

export interface Company {
  id: number;
  name: string;
  ticker: string;
  sector: Sector;
  domain: string;
  emissionsIntensity: number;
  energyEfficiency: number;
  greenCapex: number;
  carbonSensitivity: number;
  trackRecord: number;
  rdGreen: number;
}

// Real S&P 500 companies with their domains for logo fetching
const SP500_LIST: [string, string, Sector, string][] = [
  // Finance
  ["JPMorgan Chase", "JPM", "Finance", "jpmorganchase.com"],
  ["Berkshire Hathaway", "BRK.B", "Finance", "berkshirehathaway.com"],
  ["Bank of America", "BAC", "Finance", "bankofamerica.com"],
  ["Wells Fargo", "WFC", "Finance", "wellsfargo.com"],
  ["Goldman Sachs", "GS", "Finance", "goldmansachs.com"],
  ["Morgan Stanley", "MS", "Finance", "morganstanley.com"],
  ["Citigroup", "C", "Finance", "citigroup.com"],
  ["BlackRock", "BLK", "Finance", "blackrock.com"],
  ["American Express", "AXP", "Finance", "americanexpress.com"],
  ["Charles Schwab", "SCHW", "Finance", "schwab.com"],
  ["US Bancorp", "USB", "Finance", "usbank.com"],
  ["PNC Financial", "PNC", "Finance", "pnc.com"],
  ["Truist Financial", "TFC", "Finance", "truist.com"],
  ["Intercontinental Exchange", "ICE", "Finance", "theice.com"],
  ["CME Group", "CME", "Finance", "cmegroup.com"],
  ["Chubb", "CB", "Finance", "chubb.com"],
  ["Marsh & McLennan", "MMC", "Finance", "mmc.com"],
  ["Aon", "AON", "Finance", "aon.com"],
  ["MetLife", "MET", "Finance", "metlife.com"],
  ["Prudential Financial", "PRU", "Finance", "prudential.com"],
  ["Aflac", "AFL", "Finance", "aflac.com"],
  ["Hartford Financial", "HIG", "Finance", "thehartford.com"],
  ["Travelers Companies", "TRV", "Finance", "travelers.com"],
  ["Allstate", "ALL", "Finance", "allstate.com"],
  ["T. Rowe Price", "TROW", "Finance", "troweprice.com"],
  ["Franklin Resources", "BEN", "Finance", "franklinresources.com"],
  ["Invesco", "IVZ", "Finance", "invesco.com"],
  ["Ameriprise Financial", "AMP", "Finance", "ameriprise.com"],
  ["Raymond James", "RJF", "Finance", "raymondjames.com"],
  ["Regions Financial", "RF", "Finance", "regions.com"],
  ["KeyCorp", "KEY", "Finance", "key.com"],
  ["Huntington Bancshares", "HBAN", "Finance", "huntington.com"],
  ["Fifth Third Bancorp", "FITB", "Finance", "53.com"],
  ["Citizens Financial", "CFG", "Finance", "citizensbank.com"],
  ["M&T Bank", "MTB", "Finance", "mtb.com"],
  ["Synchrony Financial", "SYF", "Finance", "synchrony.com"],
  ["Capital One", "COF", "Finance", "capitalone.com"],
  ["Discover Financial", "DFS", "Finance", "discover.com"],
  ["Visa", "V", "Finance", "visa.com"],
  ["Mastercard", "MA", "Finance", "mastercard.com"],
  ["PayPal Holdings", "PYPL", "Finance", "paypal.com"],
  ["Fidelity National Info Svcs", "FIS", "Finance", "fisglobal.com"],
  ["Fiserv", "FISV", "Finance", "fiserv.com"],
  ["Global Payments", "GPN", "Finance", "globalpayments.com"],
  ["Moody's Corporation", "MCO", "Finance", "moodys.com"],
  ["S&P Global", "SPGI", "Finance", "spglobal.com"],
  ["MSCI Inc", "MSCI", "Finance", "msci.com"],
  ["Nasdaq Inc", "NDAQ", "Finance", "nasdaq.com"],
  ["Cboe Global Markets", "CBOE", "Finance", "cboe.com"],
  ["Apollo Global Management", "APO", "Finance", "apollo.com"],
  ["KKR & Co", "KKR", "Finance", "kkr.com"],
  ["Blackstone", "BX", "Finance", "blackstone.com"],
  ["Carlyle Group", "CG", "Finance", "carlyle.com"],
  ["Ares Management", "ARES", "Finance", "aresmgmt.com"],
  ["Principal Financial", "PFG", "Finance", "principal.com"],
  ["Lincoln National", "LNC", "Finance", "lfg.com"],
  ["Unum Group", "UNM", "Finance", "unum.com"],
  ["W.R. Berkley", "WRB", "Finance", "berkley.com"],
  ["Cincinnati Financial", "CINF", "Finance", "cinfin.com"],
  ["Globe Life", "GL", "Finance", "globelifeinc.com"],
  ["Assurant", "AIZ", "Finance", "assurant.com"],
  ["Willis Towers Watson", "WTW", "Finance", "wtwco.com"],
  ["Arthur J. Gallagher", "AJG", "Finance", "ajg.com"],
  ["Brown & Brown", "BRO", "Finance", "bbinsurance.com"],
  ["Prologis", "PLD", "Finance", "prologis.com"],
  ["American Tower", "AMT", "Finance", "americantower.com"],
  ["Crown Castle", "CCI", "Finance", "crowncastle.com"],
  ["Equinix", "EQIX", "Finance", "equinix.com"],
  ["Public Storage", "PSA", "Finance", "publicstorage.com"],
  ["Welltower", "WELL", "Finance", "welltower.com"],
  ["SBA Communications", "SBAC", "Finance", "sbasite.com"],
  ["Simon Property Group", "SPG", "Finance", "simon.com"],
  ["Realty Income", "O", "Finance", "realtyincome.com"],
  ["CBRE Group", "CBRE", "Finance", "cbre.com"],
  ["AvalonBay Communities", "AVB", "Finance", "avalonbay.com"],
  ["Equity Residential", "EQR", "Finance", "equityapartments.com"],
  ["Iron Mountain", "IRM", "Finance", "ironmountain.com"],
  ["Digital Realty Trust", "DLR", "Finance", "digitalrealty.com"],
  ["Ventas", "VTR", "Finance", "ventasreit.com"],
  ["Weyerhaeuser", "WY", "Finance", "weyerhaeuser.com"],
  ["Host Hotels", "HST", "Finance", "hosthotels.com"],
  ["Jack Henry & Associates", "JKHY", "Finance", "jackhenry.com"],
  ["FactSet Research", "FDS", "Finance", "factset.com"],
  ["Markel Corporation", "MKL", "Finance", "markel.com"],
  ["Everest Re Group", "EG", "Finance", "everestgre.com"],
  // Tech
  ["Apple", "AAPL", "Tech", "apple.com"],
  ["Microsoft", "MSFT", "Tech", "microsoft.com"],
  ["NVIDIA", "NVDA", "Tech", "nvidia.com"],
  ["Alphabet", "GOOGL", "Tech", "abc.xyz"],
  ["Meta Platforms", "META", "Tech", "meta.com"],
  ["Amazon", "AMZN", "Tech", "amazon.com"],
  ["Broadcom", "AVGO", "Tech", "broadcom.com"],
  ["Intel", "INTC", "Tech", "intel.com"],
  ["AMD", "AMD", "Tech", "amd.com"],
  ["Qualcomm", "QCOM", "Tech", "qualcomm.com"],
  ["Texas Instruments", "TXN", "Tech", "ti.com"],
  ["Micron Technology", "MU", "Tech", "micron.com"],
  ["Applied Materials", "AMAT", "Tech", "appliedmaterials.com"],
  ["Lam Research", "LRCX", "Tech", "lamresearch.com"],
  ["KLA Corporation", "KLAC", "Tech", "kla.com"],
  ["Marvell Technology", "MRVL", "Tech", "marvell.com"],
  ["Analog Devices", "ADI", "Tech", "analog.com"],
  ["Microchip Technology", "MCHP", "Tech", "microchip.com"],
  ["ON Semiconductor", "ON", "Tech", "onsemi.com"],
  ["Skyworks Solutions", "SWKS", "Tech", "skyworksinc.com"],
  ["Monolithic Power", "MPWR", "Tech", "monolithicpower.com"],
  ["Teradyne", "TER", "Tech", "teradyne.com"],
  ["Entegris", "ENTG", "Tech", "entegris.com"],
  ["Salesforce", "CRM", "Tech", "salesforce.com"],
  ["Oracle", "ORCL", "Tech", "oracle.com"],
  ["ServiceNow", "NOW", "Tech", "servicenow.com"],
  ["Workday", "WDAY", "Tech", "workday.com"],
  ["Snowflake", "SNOW", "Tech", "snowflake.com"],
  ["MongoDB", "MDB", "Tech", "mongodb.com"],
  ["HubSpot", "HUBS", "Tech", "hubspot.com"],
  ["Palantir", "PLTR", "Tech", "palantir.com"],
  ["UiPath", "PATH", "Tech", "uipath.com"],
  ["Veeva Systems", "VEEV", "Tech", "veeva.com"],
  ["Paycom Software", "PAYC", "Tech", "paycom.com"],
  ["Procore Technologies", "PCOR", "Tech", "procore.com"],
  ["Ceridian HCM", "CDAY", "Tech", "ceridian.com"],
  ["Cloudflare", "NET", "Tech", "cloudflare.com"],
  ["Akamai Technologies", "AKAM", "Tech", "akamai.com"],
  ["Zscaler", "ZS", "Tech", "zscaler.com"],
  ["CrowdStrike", "CRWD", "Tech", "crowdstrike.com"],
  ["Palo Alto Networks", "PANW", "Tech", "paloaltonetworks.com"],
  ["Fortinet", "FTNT", "Tech", "fortinet.com"],
  ["Check Point Software", "CHKP", "Tech", "checkpoint.com"],
  ["Zoom Video", "ZM", "Tech", "zoom.us"],
  ["Twilio", "TWLO", "Tech", "twilio.com"],
  ["RingCentral", "RNG", "Tech", "ringcentral.com"],
  ["Shopify", "SHOP", "Tech", "shopify.com"],
  ["GoDaddy", "GDDY", "Tech", "godaddy.com"],
  ["Uber Technologies", "UBER", "Tech", "uber.com"],
  ["Lyft", "LYFT", "Tech", "lyft.com"],
  ["DoorDash", "DASH", "Tech", "doordash.com"],
  ["Airbnb", "ABNB", "Tech", "airbnb.com"],
  ["Booking Holdings", "BKNG", "Tech", "bookingholdings.com"],
  ["Expedia Group", "EXPE", "Tech", "expediagroup.com"],
  ["TripAdvisor", "TRIP", "Tech", "tripadvisor.com"],
  ["Spotify Technology", "SPOT", "Tech", "spotify.com"],
  ["Netflix", "NFLX", "Tech", "netflix.com"],
  ["Walt Disney", "DIS", "Tech", "disney.com"],
  ["Comcast", "CMCSA", "Tech", "comcast.com"],
  ["Charter Communications", "CHTR", "Tech", "charter.com"],
  ["AT&T", "T", "Tech", "att.com"],
  ["Verizon Communications", "VZ", "Tech", "verizon.com"],
  ["T-Mobile US", "TMUS", "Tech", "t-mobile.com"],
  ["Juniper Networks", "JNPR", "Tech", "juniper.net"],
  ["F5 Inc", "FFIV", "Tech", "f5.com"],
  ["Ciena Corporation", "CIEN", "Tech", "ciena.com"],
  ["Lumentum Holdings", "LITE", "Tech", "lumentum.com"],
  ["II-VI Incorporated", "IIVI", "Tech", "ii-vi.com"],
  ["Coherent Corp", "COHR", "Tech", "coherent.com"],
  ["Flex Ltd", "FLEX", "Tech", "flex.com"],
  ["Jabil Inc", "JBL", "Tech", "jabil.com"],
  ["Celestica", "CLS", "Tech", "celestica.com"],
  ["Sanmina Corporation", "SANM", "Tech", "sanmina.com"],
  ["Benchmark Electronics", "BHE", "Tech", "bench.com"],
  ["Trimble Inc", "TRMB", "Tech", "trimble.com"],
  ["Zebra Technologies", "ZBRA", "Tech", "zebra.com"],
  ["Cognex Corporation", "CGNX", "Tech", "cognex.com"],
  ["National Instruments", "NATI", "Tech", "ni.com"],
  ["Keysight Technologies", "KEYS", "Tech", "keysight.com"],
  ["Xerox Holdings", "XRX", "Tech", "xerox.com"],
  ["HP Inc", "HPQ", "Tech", "hp.com"],
  ["Hewlett Packard Enterprise", "HPE", "Tech", "hpe.com"],
  ["Dell Technologies", "DELL", "Tech", "dell.com"],
  ["Seagate Technology", "STX", "Tech", "seagate.com"],
  ["Western Digital", "WDC", "Tech", "westerndigital.com"],
  ["NetApp", "NTAP", "Tech", "netapp.com"],
  ["Pure Storage", "PSTG", "Tech", "purestorage.com"],
  // Industrial
  ["Caterpillar", "CAT", "Industrial", "caterpillar.com"],
  ["Deere & Company", "DE", "Industrial", "deere.com"],
  ["Honeywell International", "HON", "Industrial", "honeywell.com"],
  ["3M Company", "MMM", "Industrial", "3m.com"],
  ["Emerson Electric", "EMR", "Industrial", "emerson.com"],
  ["Parker Hannifin", "PH", "Industrial", "parker.com"],
  ["Eaton Corporation", "ETN", "Industrial", "eaton.com"],
  ["Illinois Tool Works", "ITW", "Industrial", "itw.com"],
  ["Rockwell Automation", "ROK", "Industrial", "rockwellautomation.com"],
  ["Ametek", "AME", "Industrial", "ametek.com"],
  ["General Electric", "GE", "Industrial", "ge.com"],
  ["Boeing", "BA", "Industrial", "boeing.com"],
  ["Lockheed Martin", "LMT", "Industrial", "lockheedmartin.com"],
  ["Raytheon Technologies", "RTX", "Industrial", "rtx.com"],
  ["Northrop Grumman", "NOC", "Industrial", "northropgrumman.com"],
  ["General Dynamics", "GD", "Industrial", "gd.com"],
  ["L3Harris Technologies", "LHX", "Industrial", "l3harris.com"],
  ["Textron", "TXT", "Industrial", "textron.com"],
  ["TransDigm Group", "TDG", "Industrial", "transdigm.com"],
  ["Heico Corporation", "HEI", "Industrial", "heico.com"],
  ["Curtiss-Wright", "CW", "Industrial", "curtisswright.com"],
  ["FedEx", "FDX", "Industrial", "fedex.com"],
  ["UPS", "UPS", "Industrial", "ups.com"],
  ["CSX Corporation", "CSX", "Industrial", "csx.com"],
  ["Union Pacific", "UNP", "Industrial", "up.com"],
  ["Norfolk Southern", "NSC", "Industrial", "norfolksouthern.com"],
  ["Ryder System", "R", "Industrial", "ryder.com"],
  ["XPO Logistics", "XPO", "Industrial", "xpo.com"],
  ["J.B. Hunt Transport", "JBHT", "Industrial", "jbhunt.com"],
  ["Werner Enterprises", "WERN", "Industrial", "werner.com"],
  ["Waste Management", "WM", "Industrial", "wm.com"],
  ["Republic Services", "RSG", "Industrial", "republicservices.com"],
  ["Clean Harbors", "CLH", "Industrial", "cleanharbors.com"],
  ["Casella Waste Systems", "CWST", "Industrial", "casella.com"],
  ["Fluor Corporation", "FLR", "Industrial", "fluor.com"],
  ["Jacobs Engineering", "J", "Industrial", "jacobs.com"],
  ["Aecom", "ACM", "Industrial", "aecom.com"],
  ["KBR Inc", "KBR", "Industrial", "kbr.com"],
  ["Parsons Corporation", "PSN", "Industrial", "parsons.com"],
  ["Leidos Holdings", "LDOS", "Industrial", "leidos.com"],
  ["SAIC", "SAIC", "Industrial", "saic.com"],
  ["Booz Allen Hamilton", "BAH", "Industrial", "boozallen.com"],
  ["Danaher", "DHR", "Industrial", "danaher.com"],
  ["Waters Corporation", "WAT", "Industrial", "waters.com"],
  ["Mettler-Toledo", "MTD", "Industrial", "mt.com"],
  ["Xylem", "XYL", "Industrial", "xylem.com"],
  ["Pentair", "PNR", "Industrial", "pentair.com"],
  ["Roper Technologies", "ROP", "Industrial", "ropertech.com"],
  ["IDEX Corporation", "IEX", "Industrial", "idexcorp.com"],
  ["Chart Industries", "GTLS", "Industrial", "chartindustries.com"],
  ["Watts Water Technologies", "WTS", "Industrial", "wattswater.com"],
  ["Vulcan Materials", "VMC", "Industrial", "vulcanmaterials.com"],
  ["Martin Marietta Materials", "MLM", "Industrial", "martinmarietta.com"],
  ["Summit Materials", "SUM", "Industrial", "summit-materials.com"],
  ["Eagle Materials", "EXP", "Industrial", "eaglematerials.com"],
  ["Nucor Corporation", "NUE", "Industrial", "nucor.com"],
  ["Steel Dynamics", "STLD", "Industrial", "steeldynamics.com"],
  ["Cleveland-Cliffs", "CLF", "Industrial", "clevelandcliffs.com"],
  ["Commercial Metals", "CMC", "Industrial", "cmc.com"],
  ["Reliance Steel", "RS", "Industrial", "rsac.com"],
  ["Newmont Corporation", "NEM", "Industrial", "newmont.com"],
  ["Freeport-McMoRan", "FCX", "Industrial", "fcx.com"],
  ["Albemarle Corporation", "ALB", "Industrial", "albemarle.com"],
  ["Celanese Corporation", "CE", "Industrial", "celanese.com"],
  ["Eastman Chemical", "EMN", "Industrial", "eastman.com"],
  ["RPM International", "RPM", "Industrial", "rpminc.com"],
  ["Sherwin-Williams", "SHW", "Industrial", "sherwin-williams.com"],
  ["PPG Industries", "PPG", "Industrial", "ppg.com"],
  ["Axalta Coating Systems", "AXTA", "Industrial", "axaltacs.com"],
  ["Avery Dennison", "AVY", "Industrial", "averydennison.com"],
  ["Sealed Air", "SEE", "Industrial", "sealedair.com"],
  ["AptarGroup", "ATR", "Industrial", "aptar.com"],
  ["Greif", "GEF", "Industrial", "greif.com"],
  ["Crown Holdings", "CCK", "Industrial", "crowncork.com"],
  ["Ball Corporation", "BALL", "Industrial", "ball.com"],
  ["Silgan Holdings", "SLGN", "Industrial", "silgan.com"],
  ["Sonoco Products", "SON", "Industrial", "sonoco.com"],
  ["Packaging Corp of America", "PKG", "Industrial", "packagingcorp.com"],
  ["International Paper", "IP", "Industrial", "internationalpaper.com"],
  ["WestRock", "WRK", "Industrial", "westrock.com"],
  ["Graphic Packaging", "GPK", "Industrial", "graphicpkg.com"],
  ["Olin Corporation", "OLN", "Industrial", "olinchemicals.com"],
  ["Dow Inc", "DOW", "Industrial", "dow.com"],
  ["LyondellBasell", "LYB", "Industrial", "lyondellbasell.com"],
  ["Huntsman Corporation", "HUN", "Industrial", "huntsman.com"],
  ["Cabot Corporation", "CBT", "Industrial", "cabotcorp.com"],
  // Energy
  ["ExxonMobil", "XOM", "Energy", "exxonmobil.com"],
  ["Chevron", "CVX", "Energy", "chevron.com"],
  ["ConocoPhillips", "COP", "Energy", "conocophillips.com"],
  ["Marathon Petroleum", "MPC", "Energy", "marathonpetroleum.com"],
  ["Valero Energy", "VLO", "Energy", "valero.com"],
  ["Phillips 66", "PSX", "Energy", "phillips66.com"],
  ["Pioneer Natural Resources", "PXD", "Energy", "pxd.com"],
  ["EOG Resources", "EOG", "Energy", "eogresources.com"],
  ["Devon Energy", "DVN", "Energy", "devonenergy.com"],
  ["Coterra Energy", "CTRA", "Energy", "coterra.com"],
  ["Diamondback Energy", "FANG", "Energy", "diamondbackenergy.com"],
  ["Occidental Petroleum", "OXY", "Energy", "oxy.com"],
  ["APA Corporation", "APA", "Energy", "apacorp.com"],
  ["Callon Petroleum", "CPE", "Energy", "callon.com"],
  ["Matador Resources", "MTDR", "Energy", "matadorresources.com"],
  ["Civitas Resources", "CIVI", "Energy", "civitasresources.com"],
  ["NextEra Energy", "NEE", "Energy", "nexteraenergy.com"],
  ["Duke Energy", "DUK", "Energy", "duke-energy.com"],
  ["Southern Company", "SO", "Energy", "southerncompany.com"],
  ["Dominion Energy", "D", "Energy", "dominionenergy.com"],
  ["Exelon", "EXC", "Energy", "exeloncorp.com"],
  ["Sempra Energy", "SRE", "Energy", "sempra.com"],
  ["American Electric Power", "AEP", "Energy", "aep.com"],
  ["Entergy", "ETR", "Energy", "entergy.com"],
  ["Consolidated Edison", "ED", "Energy", "conedison.com"],
  ["Xcel Energy", "XEL", "Energy", "xcelenergy.com"],
  ["WEC Energy Group", "WEC", "Energy", "wecenergygroup.com"],
  ["Evergy", "EVRG", "Energy", "evergy.com"],
  ["Enphase Energy", "ENPH", "Energy", "enphase.com"],
  ["SolarEdge Technologies", "SEDG", "Energy", "solaredge.com"],
  ["First Solar", "FSLR", "Energy", "firstsolar.com"],
  ["Sunrun", "RUN", "Energy", "sunrun.com"],
  ["Array Technologies", "ARRY", "Energy", "arraytechinc.com"],
  ["Nextracker", "NXT", "Energy", "nextracker.com"],
  ["Kinder Morgan", "KMI", "Energy", "kindermorgan.com"],
  ["Williams Companies", "WMB", "Energy", "williams.com"],
  ["Energy Transfer", "ET", "Energy", "energytransfer.com"],
  ["Targa Resources", "TRGP", "Energy", "targaresources.com"],
  ["DT Midstream", "DTM", "Energy", "dtmidstream.com"],
  ["Halliburton", "HAL", "Energy", "halliburton.com"],
  ["SLB", "SLB", "Energy", "slb.com"],
  ["Baker Hughes", "BKR", "Energy", "bakerhughes.com"],
  ["Bloom Energy", "BE", "Energy", "bloomenergy.com"],
  ["Plug Power", "PLUG", "Energy", "plugpower.com"],
  ["Ballard Power Systems", "BLDP", "Energy", "ballard.com"],
  // Healthcare
  ["Johnson & Johnson", "JNJ", "Healthcare", "jnj.com"],
  ["Pfizer", "PFE", "Healthcare", "pfizer.com"],
  ["AbbVie", "ABBV", "Healthcare", "abbvie.com"],
  ["Merck & Co", "MRK", "Healthcare", "merck.com"],
  ["Bristol-Myers Squibb", "BMY", "Healthcare", "bms.com"],
  ["Eli Lilly", "LLY", "Healthcare", "lilly.com"],
  ["Moderna", "MRNA", "Healthcare", "modernatx.com"],
  ["Regeneron Pharmaceuticals", "REGN", "Healthcare", "regeneron.com"],
  ["Vertex Pharmaceuticals", "VRTX", "Healthcare", "vrtx.com"],
  ["Biogen", "BIIB", "Healthcare", "biogen.com"],
  ["Gilead Sciences", "GILD", "Healthcare", "gilead.com"],
  ["Amgen", "AMGN", "Healthcare", "amgen.com"],
  ["Alnylam Pharmaceuticals", "ALNY", "Healthcare", "alnylam.com"],
  ["Neurocrine Biosciences", "NBIX", "Healthcare", "neurocrine.com"],
  ["Incyte Corporation", "INCY", "Healthcare", "incyte.com"],
  ["Exelixis", "EXEL", "Healthcare", "exelixis.com"],
  ["Blueprint Medicines", "BPMC", "Healthcare", "blueprintmedicines.com"],
  ["Sage Therapeutics", "SAGE", "Healthcare", "sagerx.com"],
  ["Karuna Therapeutics", "KRTX", "Healthcare", "karunatx.com"],
  ["UnitedHealth Group", "UNH", "Healthcare", "unitedhealthgroup.com"],
  ["CVS Health", "CVS", "Healthcare", "cvshealth.com"],
  ["Cigna Group", "CI", "Healthcare", "cigna.com"],
  ["Elevance Health", "ELV", "Healthcare", "elevancehealth.com"],
  ["Humana", "HUM", "Healthcare", "humana.com"],
  ["Centene Corporation", "CNC", "Healthcare", "centene.com"],
  ["Molina Healthcare", "MOH", "Healthcare", "molinahealthcare.com"],
  ["Medtronic", "MDT", "Healthcare", "medtronic.com"],
  ["Abbott Laboratories", "ABT", "Healthcare", "abbott.com"],
  ["Boston Scientific", "BSX", "Healthcare", "bostonscientific.com"],
  ["Stryker", "SYK", "Healthcare", "stryker.com"],
  ["Edwards Lifesciences", "EW", "Healthcare", "edwards.com"],
  ["Zimmer Biomet", "ZBH", "Healthcare", "zimmerbiomet.com"],
  ["Becton Dickinson", "BDX", "Healthcare", "bd.com"],
  ["Baxter International", "BAX", "Healthcare", "baxter.com"],
  ["Hologic", "HOLX", "Healthcare", "hologic.com"],
  ["ICU Medical", "ICUI", "Healthcare", "icumedical.com"],
  ["Haemonetics", "HAE", "Healthcare", "haemonetics.com"],
  ["Integra LifeSciences", "IART", "Healthcare", "integralife.com"],
  ["Thermo Fisher Scientific", "TMO", "Healthcare", "thermofisher.com"],
  ["Agilent Technologies", "A", "Healthcare", "agilent.com"],
  ["Illumina", "ILMN", "Healthcare", "illumina.com"],
  ["Bio-Techne", "TECH", "Healthcare", "bio-techne.com"],
  ["Repligen", "RGEN", "Healthcare", "repligen.com"],
  ["West Pharmaceutical", "WST", "Healthcare", "westpharma.com"],
  ["Steris", "STE", "Healthcare", "steris.com"],
  ["Teleflex", "TFX", "Healthcare", "teleflex.com"],
  ["McKesson Corporation", "MCK", "Healthcare", "mckesson.com"],
  ["AmerisourceBergen", "ABC", "Healthcare", "amerisourcebergen.com"],
  ["Cardinal Health", "CAH", "Healthcare", "cardinalhealth.com"],
  ["Henry Schein", "HSIC", "Healthcare", "henryschein.com"],
  ["Patterson Companies", "PDCO", "Healthcare", "pattersoncompanies.com"],
  ["HCA Healthcare", "HCA", "Healthcare", "hcahealthcare.com"],
  ["Tenet Healthcare", "THC", "Healthcare", "tenethealth.com"],
  ["Universal Health Services", "UHS", "Healthcare", "uhsinc.com"],
  ["Acadia Healthcare", "ACHC", "Healthcare", "acadiahealthcare.com"],
  ["Encompass Health", "EHC", "Healthcare", "encompasshealth.com"],
  ["DaVita", "DVA", "Healthcare", "davita.com"],
  ["LHC Group", "LHCG", "Healthcare", "lhcgroup.com"],
  ["Option Care Health", "OPCH", "Healthcare", "optioncarehealth.com"],
  ["Chemed Corporation", "CHE", "Healthcare", "chemed.com"],
  ["Pediatrix Medical Group", "MD", "Healthcare", "pediatrix.com"],
  ["Surgery Partners", "SGRY", "Healthcare", "surgerypartners.com"],
  ["National HealthCare", "NHC", "Healthcare", "nhccare.com"],
  ["InvaGen Pharmaceuticals", "IPIX", "Healthcare", "innovation-biopharma.com"],
  ["Coherus Biosciences", "CHRS", "Healthcare", "coherus.com"],
  ["Novavax", "NVAX", "Healthcare", "novavax.com"],
  ["Viatris", "VTRS", "Healthcare", "viatris.com"],
  ["Perrigo Company", "PRGO", "Healthcare", "perrigo.com"],
  ["Organon & Co", "OGN", "Healthcare", "organon.com"],
  ["Jazz Pharmaceuticals", "JAZZ", "Healthcare", "jazzpharma.com"],
  ["Prestige Consumer Healthcare", "PBH", "Healthcare", "prestigeconsumerhealthcare.com"],
  // Consumer
  ["Walmart", "WMT", "Consumer", "walmart.com"],
  ["Target Corporation", "TGT", "Consumer", "target.com"],
  ["Costco Wholesale", "COST", "Consumer", "costco.com"],
  ["Home Depot", "HD", "Consumer", "homedepot.com"],
  ["Lowe's Companies", "LOW", "Consumer", "lowes.com"],
  ["Best Buy", "BBY", "Consumer", "bestbuy.com"],
  ["Kroger", "KR", "Consumer", "kroger.com"],
  ["Albertsons", "ACI", "Consumer", "albertsonscompanies.com"],
  ["Dollar General", "DG", "Consumer", "dollargeneral.com"],
  ["Dollar Tree", "DLTR", "Consumer", "dollartree.com"],
  ["Five Below", "FIVE", "Consumer", "fivebelow.com"],
  ["BJ's Wholesale Club", "BJ", "Consumer", "bjs.com"],
  ["Procter & Gamble", "PG", "Consumer", "pg.com"],
  ["Coca-Cola", "KO", "Consumer", "coca-cola.com"],
  ["PepsiCo", "PEP", "Consumer", "pepsico.com"],
  ["Mondelez International", "MDLZ", "Consumer", "mondelezinternational.com"],
  ["Colgate-Palmolive", "CL", "Consumer", "colgatepalmolive.com"],
  ["Kimberly-Clark", "KMB", "Consumer", "kimberly-clark.com"],
  ["Church & Dwight", "CHD", "Consumer", "churchdwight.com"],
  ["Energizer Holdings", "ENR", "Consumer", "energizer.com"],
  ["Spectrum Brands", "SPB", "Consumer", "spectrumbrands.com"],
  ["Clorox Company", "CLX", "Consumer", "thecloroxcompany.com"],
  ["Henkel AG (ADR)", "HENKY", "Consumer", "henkel.com"],
  ["Reckitt Benckiser (ADR)", "RBGLY", "Consumer", "reckitt.com"],
  ["Nike", "NKE", "Consumer", "nike.com"],
  ["Under Armour", "UAA", "Consumer", "underarmour.com"],
  ["Lululemon Athletica", "LULU", "Consumer", "lululemon.com"],
  ["VF Corporation", "VFC", "Consumer", "vfc.com"],
  ["Tapestry", "TPR", "Consumer", "tapestry.com"],
  ["Capri Holdings", "CPRI", "Consumer", "capriholdings.com"],
  ["Carter's", "CRI", "Consumer", "carters.com"],
  ["Oxford Industries", "OXM", "Consumer", "oxfordinc.com"],
  ["McDonald's", "MCD", "Consumer", "mcdonalds.com"],
  ["Starbucks", "SBUX", "Consumer", "starbucks.com"],
  ["Yum! Brands", "YUM", "Consumer", "yum.com"],
  ["Restaurant Brands Intl", "QSR", "Consumer", "rbi.com"],
  ["Darden Restaurants", "DRI", "Consumer", "darden.com"],
  ["Chipotle Mexican Grill", "CMG", "Consumer", "chipotle.com"],
  ["Domino's Pizza", "DPZ", "Consumer", "dominos.com"],
  ["Papa John's International", "PZZA", "Consumer", "papajohns.com"],
  ["Wingstop", "WING", "Consumer", "wingstop.com"],
  ["General Mills", "GIS", "Consumer", "generalmills.com"],
  ["Kellanova", "K", "Consumer", "kellanova.com"],
  ["Campbell Soup", "CPB", "Consumer", "campbellsoupcompany.com"],
  ["McCormick & Co", "MKC", "Consumer", "mccormick.com"],
  ["J.M. Smucker", "SJM", "Consumer", "jmsmucker.com"],
  ["Hormel Foods", "HRL", "Consumer", "hormelfoods.com"],
  ["Tyson Foods", "TSN", "Consumer", "tysonfoods.com"],
  ["Conagra Brands", "CAG", "Consumer", "conagrabrands.com"],
  ["Lamb Weston Holdings", "LW", "Consumer", "lambweston.com"],
  ["Post Holdings", "POST", "Consumer", "postholdings.com"],
  ["Pilgrim's Pride", "PPC", "Consumer", "pilgrims.com"],
  ["Treehouse Foods", "THS", "Consumer", "treehousefoods.com"],
  ["B&G Foods", "BGS", "Consumer", "bgfoods.com"],
  ["Ford Motor", "F", "Consumer", "ford.com"],
  ["General Motors", "GM", "Consumer", "gm.com"],
  ["Rivian Automotive", "RIVN", "Consumer", "rivian.com"],
  ["Lucid Group", "LCID", "Consumer", "lucidmotors.com"],
  ["Harley-Davidson", "HOG", "Consumer", "harley-davidson.com"],
  ["Thor Industries", "THO", "Consumer", "thorindustries.com"],
  ["Polaris Inc", "PII", "Consumer", "polaris.com"],
  ["Marriott International", "MAR", "Consumer", "marriott.com"],
  ["Hilton Worldwide", "HLT", "Consumer", "hilton.com"],
  ["Hyatt Hotels", "H", "Consumer", "hyatt.com"],
  ["MGM Resorts", "MGM", "Consumer", "mgmresorts.com"],
  ["Las Vegas Sands", "LVS", "Consumer", "sands.com"],
  ["Wynn Resorts", "WYNN", "Consumer", "wynnresorts.com"],
  ["Penn Entertainment", "PENN", "Consumer", "pennentertainment.com"],
  ["Royal Caribbean Group", "RCL", "Consumer", "royalcaribbeangroup.com"],
  ["Carnival Corporation", "CCL", "Consumer", "carnivalcorp.com"],
  ["Norwegian Cruise Line", "NCLH", "Consumer", "nclhltd.com"],
  ["Airbus (ADR)", "EADSY", "Consumer", "airbus.com"],
  ["Tesla", "TSLA", "Consumer", "tesla.com"],
];

function seededRandom(seed: number): () => number {
  let s = seed;
  return () => {
    s = (s * 1664525 + 1013904223) & 0xffffffff;
    return (s >>> 0) / 0xffffffff;
  };
}

const SECTOR_BIAS: Record<Sector, Record<string, number>> = {
  Finance:    { emissionsIntensity: 18, energyEfficiency: 72, greenCapex: 52, carbonSensitivity: 28, trackRecord: 62, rdGreen: 48 },
  Tech:       { emissionsIntensity: 28, energyEfficiency: 78, greenCapex: 62, carbonSensitivity: 22, trackRecord: 66, rdGreen: 78 },
  Industrial: { emissionsIntensity: 68, energyEfficiency: 44, greenCapex: 32, carbonSensitivity: 72, trackRecord: 38, rdGreen: 32 },
  Energy:     { emissionsIntensity: 82, energyEfficiency: 32, greenCapex: 48, carbonSensitivity: 88, trackRecord: 28, rdGreen: 54 },
  Healthcare: { emissionsIntensity: 32, energyEfficiency: 62, greenCapex: 44, carbonSensitivity: 32, trackRecord: 58, rdGreen: 68 },
  Consumer:   { emissionsIntensity: 52, energyEfficiency: 54, greenCapex: 38, carbonSensitivity: 56, trackRecord: 48, rdGreen: 38 },
};

export const ALL_COMPANIES: Company[] = (() => {
  const rand = seededRandom(1337);
  return SP500_LIST.map(([name, ticker, sector, domain], i) => {
    const bias = SECTOR_BIAS[sector];
    const jitter = (base: number) => Math.min(100, Math.max(0, Math.round(base + (rand() - 0.5) * 55)));
    return {
      id: i,
      name,
      ticker,
      sector,
      domain,
      emissionsIntensity: jitter(bias.emissionsIntensity),
      energyEfficiency: jitter(bias.energyEfficiency),
      greenCapex: jitter(bias.greenCapex),
      carbonSensitivity: jitter(bias.carbonSensitivity),
      trackRecord: jitter(bias.trackRecord),
      rdGreen: jitter(bias.rdGreen),
    };
  });
})();
