import { SECTORS,type Sector } from "../sp500";
type Tab="All"|Sector;export type View="dashboard"|"portfolio"|"netzero";
interface Props{activeTab:Tab;onTabChange:(tab:Tab)=>void;count:number;searchQuery:string;onSearchQueryChange:(q:string)=>void;view:View;onViewChange:(v:View)=>void}
function SearchIcon(){return <svg width="16" height="16" viewBox="0 0 16 16" fill="none"><circle cx="7" cy="7" r="5.25" stroke="currentColor" strokeWidth="1.4"/><path d="m11 11 3.5 3.5" stroke="currentColor" strokeWidth="1.4" strokeLinecap="round"/></svg>}
const titles:Record<View,[string,string]>={
 dashboard:["S&P 500 Sustainability Index","companies"],
 portfolio:["Personal Portfolio","Build around your sustainability priorities"],
 netzero:["Net-Zero Fund","Constrained climate-transition portfolio"]
};
export default function AppToolbar({activeTab,onTabChange,count,searchQuery,onSearchQueryChange,view,onViewChange}:Props){const tabs:Tab[]=["All",...SECTORS];return <header><div className="local-nav"><div className="apple-shell local-nav-inner"><div className="wordmark"><span>green</span>500</div><nav className="view-tabs"><button className={view==="dashboard"?"active":""} onClick={()=>onViewChange("dashboard")}>Index dashboard</button><button className={view==="portfolio"?"active":""} onClick={()=>onViewChange("portfolio")}>Personal allocation</button><button className={view==="netzero"?"active":""} onClick={()=>onViewChange("netzero")}>Net-zero fund</button></nav><span className="updated">Updated September 2026</span></div></div><div className="apple-shell hero-row"><div><h1>{titles[view][0]}</h1><p>{view==="dashboard"?`${count} ${titles[view][1]}`:titles[view][1]}</p></div><div className="hero-actions">{view==="dashboard"&&<label className="sector-select"><span>Sectors</span><select value={activeTab} onChange={e=>onTabChange(e.target.value as Tab)}>{tabs.map(tab=><option key={tab} value={tab}>{tab==="All"?"All sectors":tab}</option>)}</select></label>}<label className="search"><SearchIcon/><input type="search" value={searchQuery} onChange={e=>onSearchQueryChange(e.target.value)} placeholder="Search company or ticker"/></label></div></div></header>}