import { useMemo,useState } from "react";
import type { Company,Sector } from "../sp500";
import { scoreAndRank,type SustainabilityWeights } from "../scoring";
interface Props{companies:Company[];weights:SustainabilityWeights}
const COLORS=["#79ab52","#0071e3","#af52de","#ff9500","#5ac8fa","#ff3b30","#a2845e","#5856d6","#30b0c7","#8e8e93","#ff2d55"];
export default function PortfolioAllocator({companies,weights}:Props){
 const [amount,setAmount]=useState(10000);const [holdings,setHoldings]=useState(12);
 const rows=useMemo(()=>{const ranked=scoreAndRank(companies,weights).sort((a,b)=>b.score-a.score).slice(0,holdings);const total=ranked.reduce((s,c)=>s+Math.max(c.score,1),0);return ranked.map(c=>({...c,allocation:amount*Math.max(c.score,1)/total,share:Math.max(c.score,1)/total*100}))},[companies,weights,amount,holdings]);
 const sectors=useMemo(()=>{const map=new Map<Sector,number>();rows.forEach(r=>map.set(r.sector,(map.get(r.sector)??0)+r.share));return [...map].sort((a,b)=>b[1]-a[1])},[rows]);
 let cursor=0;const gradient=sectors.map(([sector,share],i)=>{const start=cursor;cursor+=share;return `${COLORS[i%COLORS.length]} ${start}% ${cursor}%`}).join(",");
 const money=new Intl.NumberFormat("en-CH",{style:"currency",currency:"CHF",maximumFractionDigits:0});
 return <section className="apple-shell portfolio-card"><div className="portfolio-heading"><div><p className="eyebrow">PERSONAL PORTFOLIO</p><h2>Portfolio allocator</h2><p>Build a sustainability-tilted portfolio from the highest-ranked companies using your weights.</p></div><div className="portfolio-inputs"><label>Portfolio value<input type="number" min="100" step="100" value={amount} onChange={e=>setAmount(Math.max(0,Number(e.target.value)))}/></label><label>Holdings<select value={holdings} onChange={e=>setHoldings(Number(e.target.value))}>{[5,10,12,15,20,25].map(n=><option key={n}>{n}</option>)}</select></label></div></div><div className="allocation-summary"><div className="donut" style={{background:`conic-gradient(${gradient})`}}><div><strong>{money.format(amount)}</strong><span>allocated</span></div></div><div className="sector-legend">{sectors.map(([sector,share],i)=><div key={sector}><i style={{background:COLORS[i%COLORS.length]}}/><span>{sector}</span><b>{share.toFixed(1)}%</b></div>)}</div></div><div className="allocation-table"><div className="allocation-row allocation-header"><span>Company</span><span>Score</span><span>Weight</span><span>Allocation</span></div>{rows.map((row,index)=><div className="allocation-row" key={row.id}><span><em>{index+1}</em><span><b>{row.name}</b><small>{row.ticker} · {row.sector}</small></span></span><strong>{row.score}</strong><span>{row.share.toFixed(1)}%</span><b>{money.format(row.allocation)}</b></div>)}</div><p className="portfolio-note">Illustrative allocation only—not investment advice. Sustainability scores reflect the selected materiality weights, not expected financial returns.</p></section>;
}