import type { Company, Sector } from "./data";

export type { Sector } from "./data";

type Constituent = readonly [name: string, ticker: string, sector: Sector];

const CONSTITUENTS: Constituent[] = [
  ["3M","MMM","Industrial"],
  ["A. O. Smith","AOS","Industrial"],
  ["Abbott Laboratories","ABT","Healthcare"],
  ["AbbVie","ABBV","Healthcare"],
  ["Accenture","ACN","Tech"],
  ["Adobe Inc.","ADBE","Tech"],
  ["Advanced Micro Devices","AMD","Tech"],
  ["AES Corporation","AES","Energy"],
  ["Aflac","AFL","Finance"],
  ["Agilent Technologies","A","Healthcare"],
  ["Air Products","APD","Industrial"],
  ["Airbnb","ABNB","Consumer"],
  ["Akamai Technologies","AKAM","Tech"],
  ["Albemarle Corporation","ALB","Industrial"],
  ["Alexandria Real Estate Equities","ARE","Finance"],
  ["Align Technology","ALGN","Healthcare"],
  ["Allegion","ALLE","Industrial"],
  ["Alliant Energy","LNT","Energy"],
  ["Allstate","ALL","Finance"],
  ["Alphabet Inc. (Class A)","GOOGL","Tech"],
  ["Altria","MO","Consumer"],
  ["Amazon","AMZN","Consumer"],
  ["Amcor","AMCR","Industrial"],
  ["Ameren","AEE","Energy"],
  ["American Electric Power","AEP","Energy"],
  ["American Express","AXP","Finance"],
  ["American International Group","AIG","Finance"],
  ["American Tower","AMT","Finance"],
  ["American Water Works","AWK","Energy"],
  ["Ameriprise Financial","AMP","Finance"],
  ["Ametek","AME","Industrial"],
  ["Amgen","AMGN","Healthcare"],
  ["Amphenol","APH","Tech"],
  ["Analog Devices","ADI","Tech"],
  ["Aon plc","AON","Finance"],
  ["APA Corporation","APA","Energy"],
  ["Apollo Global Management","APO","Finance"],
  ["Apple Inc.","AAPL","Tech"],
  ["Applied Materials","AMAT","Tech"],
  ["AppLovin","APP","Tech"],
  ["Aptiv","APTV","Consumer"],
  ["Arch Capital Group","ACGL","Finance"],
  ["Archer Daniels Midland","ADM","Consumer"],
  ["Ares Management","ARES","Finance"],
  ["Arista Networks","ANET","Tech"],
  ["Arthur J. Gallagher & Co.","AJG","Finance"],
  ["Assurant","AIZ","Finance"],
  ["AT&T","T","Tech"],
  ["Atmos Energy","ATO","Energy"],
  ["Autodesk","ADSK","Tech"],
  ["Automatic Data Processing","ADP","Industrial"],
  ["AutoZone","AZO","Consumer"],
  ["Avery Dennison","AVY","Industrial"],
  ["Axon Enterprise","AXON","Industrial"],
  ["Baker Hughes","BKR","Energy"],
  ["Ball Corporation","BALL","Industrial"],
  ["Bank of America","BAC","Finance"],
  ["Baxter International","BAX","Healthcare"],
  ["Becton Dickinson","BDX","Healthcare"],
  ["Berkshire Hathaway","BRK.B","Finance"],
  ["Best Buy","BBY","Consumer"],
  ["Bio-Techne","TECH","Healthcare"],
  ["Biogen","BIIB","Healthcare"],
  ["BlackRock","BLK","Finance"],
  ["Blackstone Inc.","BX","Finance"],
  ["Block, Inc.","XYZ","Finance"],
  ["BNY Mellon","BNY","Finance"],
  ["Boeing","BA","Industrial"],
  ["Booking Holdings","BKNG","Consumer"],
  ["Boston Scientific","BSX","Healthcare"],
  ["Bristol Myers Squibb","BMY","Healthcare"],
  ["Broadcom","AVGO","Tech"],
  ["Broadridge Financial Solutions","BR","Industrial"],
  ["Brown & Brown","BRO","Finance"],
  ["Brown–Forman","BF.B","Consumer"],
  ["Builders FirstSource","BLDR","Industrial"],
  ["Bunge Global","BG","Consumer"],
  ["BXP, Inc.","BXP","Finance"],
  ["C.H. Robinson","CHRW","Industrial"],
  ["Cadence Design Systems","CDNS","Tech"],
  ["Camden Property Trust","CPT","Finance"],
  ["Capital One","COF","Finance"],
  ["Cardinal Health","CAH","Healthcare"],
  ["Carnival Corporation","CCL","Consumer"],
  ["Carrier Global","CARR","Industrial"],
  ["Carvana","CVNA","Consumer"],
  ["Casey's","CASY","Consumer"],
  ["Caterpillar Inc.","CAT","Industrial"],
  ["Cboe Global Markets","CBOE","Finance"],
  ["CBRE Group","CBRE","Finance"],
  ["CDW Corporation","CDW","Tech"],
  ["Cencora","COR","Healthcare"],
  ["Centene Corporation","CNC","Healthcare"],
  ["CenterPoint Energy","CNP","Energy"],
  ["CF Industries","CF","Industrial"],
  ["Charles River Laboratories","CRL","Healthcare"],
  ["Charles Schwab Corporation","SCHW","Finance"],
  ["Charter Communications","CHTR","Tech"],
  ["Chevron Corporation","CVX","Energy"],
  ["Chipotle Mexican Grill","CMG","Consumer"],
  ["Chubb Limited","CB","Finance"],
  ["Church & Dwight","CHD","Consumer"],
  ["Ciena","CIEN","Tech"],
  ["Cigna","CI","Healthcare"],
  ["Cincinnati Financial","CINF","Finance"],
  ["Cintas","CTAS","Industrial"],
  ["Cisco","CSCO","Tech"],
  ["Citigroup","C","Finance"],
  ["Citizens Financial Group","CFG","Finance"],
  ["Clorox","CLX","Consumer"],
  ["CME Group","CME","Finance"],
  ["CMS Energy","CMS","Energy"],
  ["Coca-Cola Company (The)","KO","Consumer"],
  ["Cognizant","CTSH","Tech"],
  ["Coherent Corp.","COHR","Tech"],
  ["Coinbase","COIN","Finance"],
  ["Colgate-Palmolive","CL","Consumer"],
  ["Comcast","CMCSA","Tech"],
  ["Comfort Systems USA","FIX","Industrial"],
  ["ConocoPhillips","COP","Energy"],
  ["Consolidated Edison","ED","Energy"],
  ["Constellation Brands","STZ","Consumer"],
  ["Constellation Energy","CEG","Energy"],
  ["Cooper Companies (The)","COO","Healthcare"],
  ["Copart","CPRT","Industrial"],
  ["Corning Inc.","GLW","Tech"],
  ["Corpay","CPAY","Finance"],
  ["Corteva","CTVA","Industrial"],
  ["CoStar Group","CSGP","Finance"],
  ["Costco","COST","Consumer"],
  ["CRH plc","CRH","Industrial"],
  ["CrowdStrike","CRWD","Tech"],
  ["Crown Castle","CCI","Finance"],
  ["CSX Corporation","CSX","Industrial"],
  ["Cummins","CMI","Industrial"],
  ["CVS Health","CVS","Healthcare"],
  ["Danaher Corporation","DHR","Healthcare"],
  ["Darden Restaurants","DRI","Consumer"],
  ["Datadog","DDOG","Tech"],
  ["DaVita","DVA","Healthcare"],
  ["Deckers Brands","DECK","Consumer"],
  ["Deere & Company","DE","Industrial"],
  ["Dell Technologies","DELL","Tech"],
  ["Delta Air Lines","DAL","Industrial"],
  ["Devon Energy","DVN","Energy"],
  ["Dexcom","DXCM","Healthcare"],
  ["Diamondback Energy","FANG","Energy"],
  ["Digital Realty","DLR","Finance"],
  ["Dollar General","DG","Consumer"],
  ["Dollar Tree","DLTR","Consumer"],
  ["Dominion Energy","D","Energy"],
  ["Domino's","DPZ","Consumer"],
  ["DoorDash","DASH","Consumer"],
  ["Dover Corporation","DOV","Industrial"],
  ["Dow Inc.","DOW","Industrial"],
  ["D. R. Horton","DHI","Consumer"],
  ["DTE Energy","DTE","Energy"],
  ["Duke Energy","DUK","Energy"],
  ["DuPont","DD","Industrial"],
  ["Eaton Corporation","ETN","Industrial"],
  ["eBay Inc.","EBAY","Consumer"],
  ["EchoStar","ECHO","Tech"],
  ["Ecolab","ECL","Industrial"],
  ["Edison International","EIX","Energy"],
  ["Edwards Lifesciences","EW","Healthcare"],
  ["Elevance Health","ELV","Healthcare"],
  ["Emcor","EME","Industrial"],
  ["Emerson Electric","EMR","Industrial"],
  ["Entergy","ETR","Energy"],
  ["EOG Resources","EOG","Energy"],
  ["EQT Corporation","EQT","Energy"],
  ["Equifax","EFX","Industrial"],
  ["Equinix","EQIX","Finance"],
  ["Erie Indemnity","ERIE","Finance"],
  ["Essex Property Trust","ESS","Finance"],
  ["Estée Lauder Companies (The)","EL","Consumer"],
  ["Everest Group","EG","Finance"],
  ["Evergy","EVRG","Energy"],
  ["Eversource Energy","ES","Energy"],
  ["Exelon","EXC","Energy"],
  ["Expand Energy","EXE","Energy"],
  ["Expedia Group","EXPE","Consumer"],
  ["Expeditors International","EXPD","Industrial"],
  ["Extra Space Storage","EXR","Finance"],
  ["ExxonMobil","XOM","Energy"],
  ["F5, Inc.","FFIV","Tech"],
  ["FactSet","FDS","Finance"],
  ["Fair Isaac","FICO","Tech"],
  ["Fastenal","FAST","Industrial"],
  ["Federal Realty Investment Trust","FRT","Finance"],
  ["FedEx","FDX","Industrial"],
  ["FedEx Freight","FDXF","Industrial"],
  ["Ferguson Enterprises","FERG","Industrial"],
  ["Fidelity National Information Services","FIS","Finance"],
  ["Fifth Third Bancorp","FITB","Finance"],
  ["First Solar","FSLR","Tech"],
  ["FirstEnergy","FE","Energy"],
  ["Fiserv","FISV","Finance"],
  ["Flex Ltd.","FLEX","Tech"],
  ["Ford Motor Company","F","Consumer"],
  ["Fortinet","FTNT","Tech"],
  ["Fortive","FTV","Industrial"],
  ["Fox Corporation (Class A)","FOXA","Tech"],
  ["Franklin Resources","BEN","Finance"],
  ["Freeport-McMoRan","FCX","Industrial"],
  ["Garmin","GRMN","Consumer"],
  ["Gartner","IT","Tech"],
  ["GE Aerospace","GE","Industrial"],
  ["GE HealthCare","GEHC","Healthcare"],
  ["GE Vernova","GEV","Industrial"],
  ["Gen Digital","GEN","Tech"],
  ["Generac","GNRC","Industrial"],
  ["General Dynamics","GD","Industrial"],
  ["General Mills","GIS","Consumer"],
  ["General Motors","GM","Consumer"],
  ["Genuine Parts Company","GPC","Consumer"],
  ["Gilead Sciences","GILD","Healthcare"],
  ["Global Payments","GPN","Finance"],
  ["Globe Life","GL","Finance"],
  ["GoDaddy","GDDY","Tech"],
  ["Goldman Sachs","GS","Finance"],
  ["Halliburton","HAL","Energy"],
  ["Hartford (The)","HIG","Finance"],
  ["Hasbro","HAS","Consumer"],
  ["HCA Healthcare","HCA","Healthcare"],
  ["Healthpeak Properties","DOC","Finance"],
  ["Henry Schein","HSIC","Healthcare"],
  ["Hershey Company (The)","HSY","Consumer"],
  ["Hewlett Packard Enterprise","HPE","Tech"],
  ["Hilton Worldwide","HLT","Consumer"],
  ["Home Depot (The)","HD","Consumer"],
  ["Honeywell Aerospace","HONA","Industrial"],
  ["Honeywell Technologies","HON","Industrial"],
  ["Hormel Foods","HRL","Consumer"],
  ["Host Hotels & Resorts","HST","Finance"],
  ["Howmet Aerospace","HWM","Industrial"],
  ["HP Inc.","HPQ","Tech"],
  ["Hubbell Incorporated","HUBB","Industrial"],
  ["Humana","HUM","Healthcare"],
  ["Huntington Bancshares","HBAN","Finance"],
  ["Huntington Ingalls Industries","HII","Industrial"],
  ["IBM","IBM","Tech"],
  ["IDEX Corporation","IEX","Industrial"],
  ["Idexx Laboratories","IDXX","Healthcare"],
  ["Illinois Tool Works","ITW","Industrial"],
  ["Incyte","INCY","Healthcare"],
  ["Ingersoll Rand","IR","Industrial"],
  ["Insulet Corporation","PODD","Healthcare"],
  ["Intel","INTC","Tech"],
  ["Interactive Brokers","IBKR","Finance"],
  ["Intercontinental Exchange","ICE","Finance"],
  ["International Flavors & Fragrances","IFF","Industrial"],
  ["International Paper","IP","Industrial"],
  ["Intuit","INTU","Tech"],
  ["Intuitive Surgical","ISRG","Healthcare"],
  ["Invesco","IVZ","Finance"],
  ["Invitation Homes","INVH","Finance"],
  ["IQVIA","IQV","Healthcare"],
  ["Iron Mountain","IRM","Finance"],
  ["J.B. Hunt","JBHT","Industrial"],
  ["Jabil","JBL","Tech"],
  ["Jack Henry & Associates","JKHY","Finance"],
  ["Jacobs Solutions","J","Industrial"],
  ["Johnson & Johnson","JNJ","Healthcare"],
  ["Johnson Controls","JCI","Industrial"],
  ["JPMorgan Chase","JPM","Finance"],
  ["Kenvue","KVUE","Consumer"],
  ["Keurig Dr Pepper","KDP","Consumer"],
  ["KeyCorp","KEY","Finance"],
  ["Keysight Technologies","KEYS","Tech"],
  ["Kimberly-Clark","KMB","Consumer"],
  ["Kimco Realty","KIM","Finance"],
  ["Kinder Morgan","KMI","Energy"],
  ["KKR & Co.","KKR","Finance"],
  ["KLA Corporation","KLAC","Tech"],
  ["Kraft Heinz","KHC","Consumer"],
  ["Kroger","KR","Consumer"],
  ["L3Harris","LHX","Industrial"],
  ["Labcorp","LH","Healthcare"],
  ["Lam Research","LRCX","Tech"],
  ["Las Vegas Sands","LVS","Consumer"],
  ["Leidos","LDOS","Industrial"],
  ["Lennar","LEN","Consumer"],
  ["Lennox International","LII","Industrial"],
  ["Lilly (Eli)","LLY","Healthcare"],
  ["Linde plc","LIN","Industrial"],
  ["Live Nation Entertainment","LYV","Tech"],
  ["Lockheed Martin","LMT","Industrial"],
  ["Loews Corporation","L","Finance"],
  ["Lowe's","LOW","Consumer"],
  ["Lululemon Athletica","LULU","Consumer"],
  ["Lumentum","LITE","Tech"],
  ["LyondellBasell","LYB","Industrial"],
  ["M&T Bank","MTB","Finance"],
  ["Marathon Petroleum","MPC","Energy"],
  ["Marriott International","MAR","Consumer"],
  ["Marsh McLennan","MRSH","Finance"],
  ["Martin Marietta Materials","MLM","Industrial"],
  ["Marvell Technology","MRVL","Tech"],
  ["Masco","MAS","Industrial"],
  ["Mastercard","MA","Finance"],
  ["McCormick & Company","MKC","Consumer"],
  ["McDonald's","MCD","Consumer"],
  ["McKesson Corporation","MCK","Healthcare"],
  ["Medtronic","MDT","Healthcare"],
  ["Merck & Co.","MRK","Healthcare"],
  ["Meta Platforms","META","Tech"],
  ["MetLife","MET","Finance"],
  ["Mettler Toledo","MTD","Healthcare"],
  ["MGM Resorts","MGM","Consumer"],
  ["Microchip Technology","MCHP","Tech"],
  ["Micron Technology","MU","Tech"],
  ["Microsoft","MSFT","Tech"],
  ["Mid-America Apartment Communities","MAA","Finance"],
  ["Moderna","MRNA","Healthcare"],
  ["Molson Coors Beverage Company","TAP","Consumer"],
  ["Mondelez International","MDLZ","Consumer"],
  ["Monolithic Power Systems","MPWR","Tech"],
  ["Monster Beverage","MNST","Consumer"],
  ["Moody's Corporation","MCO","Finance"],
  ["Morgan Stanley","MS","Finance"],
  ["Mosaic Company (The)","MOS","Industrial"],
  ["Motorola Solutions","MSI","Tech"],
  ["MSCI","MSCI","Finance"],
  ["Nasdaq, Inc.","NDAQ","Finance"],
  ["NetApp","NTAP","Tech"],
  ["Netflix","NFLX","Tech"],
  ["Newmont","NEM","Industrial"],
  ["News Corp (Class A)","NWSA","Tech"],
  ["NextEra Energy","NEE","Energy"],
  ["Nike, Inc.","NKE","Consumer"],
  ["NiSource","NI","Energy"],
  ["Nordson Corporation","NDSN","Industrial"],
  ["Norfolk Southern","NSC","Industrial"],
  ["Northern Trust","NTRS","Finance"],
  ["Northrop Grumman","NOC","Industrial"],
  ["Norwegian Cruise Line Holdings","NCLH","Consumer"],
  ["NRG Energy","NRG","Energy"],
  ["Nucor","NUE","Industrial"],
  ["Nvidia","NVDA","Tech"],
  ["NVR, Inc.","NVR","Consumer"],
  ["NXP Semiconductors","NXPI","Tech"],
  ["O'Reilly Automotive","ORLY","Consumer"],
  ["Occidental Petroleum","OXY","Energy"],
  ["Old Dominion","ODFL","Industrial"],
  ["Omnicom Group","OMC","Tech"],
  ["ON Semiconductor","ON","Tech"],
  ["Oneok","OKE","Energy"],
  ["Oracle Corporation","ORCL","Tech"],
  ["Otis Worldwide","OTIS","Industrial"],
  ["Paccar","PCAR","Industrial"],
  ["Packaging Corporation of America","PKG","Industrial"],
  ["Palantir Technologies","PLTR","Tech"],
  ["Palo Alto Networks","PANW","Tech"],
  ["Paramount Skydance Corporation","PSKY","Tech"],
  ["Parker Hannifin","PH","Industrial"],
  ["Paychex","PAYX","Industrial"],
  ["PayPal","PYPL","Finance"],
  ["Pentair","PNR","Industrial"],
  ["PepsiCo","PEP","Consumer"],
  ["Pfizer","PFE","Healthcare"],
  ["PG&E Corporation","PCG","Energy"],
  ["Philip Morris International","PM","Consumer"],
  ["Phillips 66","PSX","Energy"],
  ["Pinnacle West Capital","PNW","Energy"],
  ["PNC Financial Services","PNC","Finance"],
  ["PPG Industries","PPG","Industrial"],
  ["PPL Corporation","PPL","Energy"],
  ["Principal Financial Group","PFG","Finance"],
  ["Procter & Gamble","PG","Consumer"],
  ["Progressive Corporation","PGR","Finance"],
  ["Prologis","PLD","Finance"],
  ["Prudential Financial","PRU","Finance"],
  ["Public Service Enterprise Group","PEG","Energy"],
  ["PTC Inc.","PTC","Tech"],
  ["Public Storage","PSA","Finance"],
  ["PulteGroup","PHM","Consumer"],
  ["Quanta Services","PWR","Industrial"],
  ["Qualcomm","QCOM","Tech"],
  ["Quest Diagnostics","DGX","Healthcare"],
  ["Qnity Electronics","Q","Tech"],
  ["Ralph Lauren Corporation","RL","Consumer"],
  ["Raymond James Financial","RJF","Finance"],
  ["Reddit","RDDT","Tech"],
  ["RTX Corporation","RTX","Industrial"],
  ["Realty Income","O","Finance"],
  ["Regency Centers","REG","Finance"],
  ["Regeneron Pharmaceuticals","REGN","Healthcare"],
  ["Regions Financial Corporation","RF","Finance"],
  ["Republic Services","RSG","Industrial"],
  ["ResMed","RMD","Healthcare"],
  ["Revvity","RVTY","Healthcare"],
  ["Robinhood Markets","HOOD","Finance"],
  ["Rockwell Automation","ROK","Industrial"],
  ["Rollins, Inc.","ROL","Industrial"],
  ["Roper Technologies","ROP","Tech"],
  ["Ross Stores","ROST","Consumer"],
  ["Royal Caribbean Group","RCL","Consumer"],
  ["S&P Global","SPGI","Finance"],
  ["Salesforce","CRM","Tech"],
  ["Sandisk","SNDK","Tech"],
  ["SBA Communications","SBAC","Finance"],
  ["Schlumberger","SLB","Energy"],
  ["Seagate Technology","STX","Tech"],
  ["Sempra","SRE","Energy"],
  ["ServiceNow","NOW","Tech"],
  ["Sherwin-Williams","SHW","Industrial"],
  ["Simon Property Group","SPG","Finance"],
  ["Skyworks Solutions","SWKS","Tech"],
  ["J.M. Smucker Company (The)","SJM","Consumer"],
  ["Smurfit Westrock","SW","Industrial"],
  ["Snap-on","SNA","Industrial"],
  ["Solventum","SOLV","Healthcare"],
  ["Southern Company","SO","Energy"],
  ["Southwest Airlines","LUV","Industrial"],
  ["Stanley Black & Decker","SWK","Industrial"],
  ["Starbucks","SBUX","Consumer"],
  ["State Street Corporation","STT","Finance"],
  ["Steel Dynamics","STLD","Industrial"],
  ["Steris","STE","Healthcare"],
  ["Stryker Corporation","SYK","Healthcare"],
  ["Supermicro","SMCI","Tech"],
  ["Synchrony Financial","SYF","Finance"],
  ["Synopsys","SNPS","Tech"],
  ["Sysco","SYY","Consumer"],
  ["T-Mobile US","TMUS","Tech"],
  ["T. Rowe Price","TROW","Finance"],
  ["Take-Two Interactive","TTWO","Tech"],
  ["Tapestry, Inc.","TPR","Consumer"],
  ["Targa Resources","TRGP","Energy"],
  ["Target Corporation","TGT","Consumer"],
  ["TE Connectivity","TEL","Tech"],
  ["Teledyne Technologies","TDY","Tech"],
  ["Teradyne","TER","Tech"],
  ["Tesla, Inc.","TSLA","Consumer"],
  ["Texas Instruments","TXN","Tech"],
  ["Texas Pacific Land Corporation","TPL","Energy"],
  ["Textron","TXT","Industrial"],
  ["Thermo Fisher Scientific","TMO","Healthcare"],
  ["TJX Companies","TJX","Consumer"],
  ["TKO Group Holdings","TKO","Tech"],
  ["Trade Desk (The)","TTD","Tech"],
  ["Tractor Supply","TSCO","Consumer"],
  ["Trane Technologies","TT","Industrial"],
  ["TransDigm Group","TDG","Industrial"],
  ["Travelers Companies (The)","TRV","Finance"],
  ["Trimble Inc.","TRMB","Tech"],
  ["Truist Financial","TFC","Finance"],
  ["Tyler Technologies","TYL","Tech"],
  ["Tyson Foods","TSN","Consumer"],
  ["U.S. Bancorp","USB","Finance"],
  ["Uber","UBER","Industrial"],
  ["UDR, Inc.","UDR","Finance"],
  ["Ulta Beauty","ULTA","Consumer"],
  ["Union Pacific Corporation","UNP","Industrial"],
  ["United Airlines Holdings","UAL","Industrial"],
  ["United Parcel Service","UPS","Industrial"],
  ["United Rentals","URI","Industrial"],
  ["UnitedHealth Group","UNH","Healthcare"],
  ["Universal Health Services","UHS","Healthcare"],
  ["Valero Energy","VLO","Energy"],
  ["Veeva Systems","VEEV","Healthcare"],
  ["Ventas","VTR","Finance"],
  ["Veralto","VLTO","Industrial"],
  ["Verisign","VRSN","Tech"],
  ["Verisk Analytics","VRSK","Industrial"],
  ["Verizon","VZ","Tech"],
  ["Vertex Pharmaceuticals","VRTX","Healthcare"],
  ["Vertiv","VRT","Industrial"],
  ["Viatris","VTRS","Healthcare"],
  ["Vici Properties","VICI","Finance"],
  ["Visa Inc.","V","Finance"],
  ["Vistra Corp.","VST","Energy"],
  ["Vivmark Residential","VMRK","Finance"],
  ["Vulcan Materials Company","VMC","Industrial"],
  ["W. R. Berkley Corporation","WRB","Finance"],
  ["W. W. Grainger","GWW","Industrial"],
  ["Wabtec","WAB","Industrial"],
  ["Walmart","WMT","Consumer"],
  ["Walt Disney Company (The)","DIS","Tech"],
  ["Warner Bros. Discovery","WBD","Tech"],
  ["Waste Management","WM","Industrial"],
  ["Waters Corporation","WAT","Healthcare"],
  ["WEC Energy Group","WEC","Energy"],
  ["Wells Fargo","WFC","Finance"],
  ["Welltower","WELL","Finance"],
  ["West Pharmaceutical Services","WST","Healthcare"],
  ["Western Digital","WDC","Tech"],
  ["Weyerhaeuser","WY","Finance"],
  ["Williams-Sonoma, Inc.","WSM","Consumer"],
  ["Williams Companies","WMB","Energy"],
  ["Willis Towers Watson","WTW","Finance"],
  ["Workday, Inc.","WDAY","Tech"],
  ["Wynn Resorts","WYNN","Consumer"],
  ["Xcel Energy","XEL","Energy"],
  ["Xylem Inc.","XYL","Industrial"],
  ["Yum! Brands","YUM","Consumer"],
  ["Zebra Technologies","ZBRA","Tech"],
  ["Zimmer Biomet","ZBH","Healthcare"],
  ["Zoetis","ZTS","Healthcare"],
];

function seededRandom(seed: number): () => number {
  let state = seed;
  return () => {
    state = (state * 1664525 + 1013904223) & 0xffffffff;
    return (state >>> 0) / 0xffffffff;
  };
}

const SECTOR_BIAS: Record<Sector, Omit<Company, "id" | "name" | "ticker" | "sector" | "domain">> = {
  Finance: { emissionsIntensity: 18, energyEfficiency: 72, greenCapex: 52, carbonSensitivity: 28, trackRecord: 62, rdGreen: 48 },
  Tech: { emissionsIntensity: 28, energyEfficiency: 78, greenCapex: 62, carbonSensitivity: 22, trackRecord: 66, rdGreen: 78 },
  Industrial: { emissionsIntensity: 68, energyEfficiency: 44, greenCapex: 32, carbonSensitivity: 72, trackRecord: 38, rdGreen: 32 },
  Energy: { emissionsIntensity: 82, energyEfficiency: 32, greenCapex: 48, carbonSensitivity: 88, trackRecord: 28, rdGreen: 54 },
  Healthcare: { emissionsIntensity: 32, energyEfficiency: 62, greenCapex: 44, carbonSensitivity: 32, trackRecord: 58, rdGreen: 68 },
  Consumer: { emissionsIntensity: 52, energyEfficiency: 54, greenCapex: 38, carbonSensitivity: 56, trackRecord: 48, rdGreen: 38 },
};

export const ALL_COMPANIES: Company[] = (() => {
  const random = seededRandom(1337);
  return CONSTITUENTS.map(([name, ticker, sector], id) => {
    const bias = SECTOR_BIAS[sector];
    const jitter = (base: number) => Math.min(100, Math.max(0, Math.round(base + (random() - 0.5) * 55)));
    return { id, name, ticker, sector, domain: "", emissionsIntensity: jitter(bias.emissionsIntensity), energyEfficiency: jitter(bias.energyEfficiency), greenCapex: jitter(bias.greenCapex), carbonSensitivity: jitter(bias.carbonSensitivity), trackRecord: jitter(bias.trackRecord), rdGreen: jitter(bias.rdGreen) };
  });
})();
